Guess country
paymentez/paymentez.js pull request #40
Opened 2020-11-27 11:39 UTC by jcmpaymentez

- Add autocomplete to country selector
- Add guess country selector function
- Fix Canada & USA flag bug

2020-11-30 20:44 UTC, cravgabo requested changes
Solo un comentario sobre el boolean y el error que se presenta en la imagen adjunta

![image](https://user-images.githubusercontent.com/36054696/100662369-6dd87280-331a-11eb-8984-0f91841cbfff.png)

2020-11-30 20:44 UTC, cravgabo commented on src/js/payment-form-js.js
> +  const options = Payment.COUNTRIES.filter(country => country.active === true);
Validas que un boolean sea verdadero, no aplica el "=== true"

2020-12-01 18:09 UTC, cravgabo requested changes
Solo quita el log, lo de la imagen toca tenerlo en mente para una mejora después, meter una validación para cuando se borra la opción, (supongo que es debido a selectize que permite borrar el registro y no requiere que se vuelva a completar)

![image](https://user-images.githubusercontent.com/36054696/100779491-172c7080-33ce-11eb-8b7f-cf512fd16afb.png)

2020-12-01 18:09 UTC, cravgabo commented on src/js/payment-form-js.js
> +    console.log(this.defaultCountryCode)
Quita el log pls

2020-12-01 19:06 UTC, jcmpaymentez commented on src/js/payment-form-js.js
> +    console.log(this.defaultCountryCode)
Done!!

2020-12-01 19:19 UTC, merged