Bug expiration date
paymentez/paymentez.js pull request #58
Opened 2021-11-05 19:36 UTC by SilviaGuerra13

2021-11-09 18:50 UTC, jcmpaymentez commented
Quedó muy bien

2021-11-09 18:50 UTC, jcmpaymentez approved these changes

2021-12-06 23:40 UTC, Leidy-pm requested changes

2021-12-06 23:40 UTC, Leidy-pm commented on src/js/payment-form-js.js
> +    let val = $this.cardNumberInput[0].value;
hay que unificar o .value o .val() :)

2021-12-06 23:40 UTC, Leidy-pm commented on src/js/payment-form-js.js
>        let val = $this.expiryMonthYearInput.val();
vamos a mandarlo en una constante para asegurar que no cambiemos el valor,  tal vez por eso lo perdemos en prod

2021-12-07 00:50 UTC, SilviaGuerra13 commented
Tarea https://paymentez.atlassian.net/browse/DEV-1525

2021-12-21 17:47 UTC, cravgabo commented on src/js/payment-form-js.js
> +    let val = $this.cardNumberInput[0].value;
En realidad depende de como se obtiene el objeto, si es por jquery o javascript puro, así cambia si es con value o val()

2021-12-21 17:47 UTC, cravgabo commented on src/js/payment-form-js.js
>        let val = $this.expiryMonthYearInput.val();
No entendí esto

2021-12-21 17:49 UTC, cravgabo commented on src/js/payment-form-js.js
> +        $this.expiryMonthYearInput.val(val.substr(0, 2) + " / " + val.substr(3, 2))
Porque cambias 4 por 2?

2021-12-21 17:52 UTC, SilviaGuerra13 commented on src/js/payment-form-js.js
> +        $this.expiryMonthYearInput.val(val.substr(0, 2) + " / " + val.substr(3, 2))
Porque el 2o parámetro de substr es la longitud (yo pensé que indicaba el indice donde terminaba pero después de leer la documentación aprendí eso)

2022-01-04 02:47 UTC, cravgabo approved these changes

2022-01-04 02:48 UTC, merged